import { Product } from '../types';

export const products: Product[] = [
  // Vegetables (10 items) - Real Indian vegetable images
  {
    id: 'veg1',
    name: 'Fresh Onions 1kg',
    price: 35,
    image: 'https://images.pexels.com/photos/1458694/pexels-photo-1458694.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Vegetables',
    brand: 'Fresh Farm',
    stock: 50,
    description: 'Fresh red onions, essential for Indian cooking',
    dietary: ['vegan', 'organic'],
    isTimeRelevant: false,
    relevantTimes: []
  },
  {
    id: 'veg2',
    name: 'Tomatoes 500g',
    price: 25,
    image: 'https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Vegetables',
    brand: 'Fresh Farm',
    stock: 40,
    description: 'Ripe red tomatoes, perfect for curries and salads',
    dietary: ['vegan', 'organic'],
    isTimeRelevant: false,
    relevantTimes: []
  },
  {
    id: 'veg3',
    name: 'Green Chilies 100g',
    price: 15,
    image: 'https://images.pexels.com/photos/1437267/pexels-photo-1437267.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Vegetables',
    brand: 'Fresh Farm',
    stock: 30,
    description: 'Fresh green chilies for that perfect spice',
    dietary: ['vegan', 'organic'],
    isTimeRelevant: false,
    relevantTimes: []
  },
  {
    id: 'veg4',
    name: 'Potatoes 1kg',
    price: 30,
    image: 'https://images.pexels.com/photos/2286776/pexels-photo-2286776.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Vegetables',
    brand: 'Fresh Farm',
    stock: 60,
    description: 'Fresh potatoes, versatile for all Indian dishes',
    dietary: ['vegan', 'organic'],
    isTimeRelevant: false,
    relevantTimes: []
  },
  {
    id: 'veg5',
    name: 'Ginger 200g',
    price: 40,
    image: 'https://images.pexels.com/photos/1435735/pexels-photo-1435735.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Vegetables',
    brand: 'Fresh Farm',
    stock: 25,
    description: 'Fresh ginger root, essential for Indian cooking',
    dietary: ['vegan', 'organic'],
    isTimeRelevant: false,
    relevantTimes: []
  },
  {
    id: 'veg6',
    name: 'Garlic 250g',
    price: 45,
    image: 'https://images.pexels.com/photos/1435735/pexels-photo-1435735.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Vegetables',
    brand: 'Fresh Farm',
    stock: 35,
    description: 'Fresh garlic bulbs for aromatic cooking',
    dietary: ['vegan', 'organic'],
    isTimeRelevant: false,
    relevantTimes: []
  },
  {
    id: 'veg7',
    name: 'Coriander Leaves 100g',
    price: 20,
    image: 'https://images.pexels.com/photos/4198019/pexels-photo-4198019.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Vegetables',
    brand: 'Fresh Farm',
    stock: 20,
    description: 'Fresh coriander leaves for garnishing',
    dietary: ['vegan', 'organic'],
    isTimeRelevant: false,
    relevantTimes: []
  },
  {
    id: 'veg8',
    name: 'Capsicum 500g',
    price: 60,
    image: 'https://images.pexels.com/photos/1268101/pexels-photo-1268101.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Vegetables',
    brand: 'Fresh Farm',
    stock: 25,
    description: 'Fresh bell peppers, colorful and nutritious',
    dietary: ['vegan', 'organic'],
    isTimeRelevant: false,
    relevantTimes: []
  },
  {
    id: 'veg9',
    name: 'Okra (Bhindi) 500g',
    price: 50,
    image: 'https://images.pexels.com/photos/4198019/pexels-photo-4198019.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Vegetables',
    brand: 'Fresh Farm',
    stock: 30,
    description: 'Fresh okra, perfect for Indian bhindi masala',
    dietary: ['vegan', 'organic'],
    isTimeRelevant: false,
    relevantTimes: []
  },
  {
    id: 'veg10',
    name: 'Spinach (Palak) 250g',
    price: 25,
    image: 'https://images.pexels.com/photos/2255935/pexels-photo-2255935.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Vegetables',
    brand: 'Fresh Farm',
    stock: 20,
    description: 'Fresh spinach leaves, rich in iron',
    dietary: ['vegan', 'organic'],
    isTimeRelevant: false,
    relevantTimes: []
  },

  // Fruits (10 items) - Real Indian fruit images
  {
    id: 'fruit1',
    name: 'Bananas 1 dozen',
    price: 60,
    image: 'https://images.pexels.com/photos/2872755/pexels-photo-2872755.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Fruits',
    brand: 'Fresh Fruits',
    stock: 40,
    description: 'Fresh ripe bananas, rich in potassium',
    dietary: ['vegan', 'organic'],
    isTimeRelevant: true,
    relevantTimes: ['morning', 'afternoon']
  },
  {
    id: 'fruit2',
    name: 'Apples 1kg',
    price: 180,
    image: 'https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Fruits',
    brand: 'Fresh Fruits',
    stock: 35,
    description: 'Crisp red apples, perfect for healthy snacking',
    dietary: ['vegan', 'organic'],
    isTimeRelevant: false,
    relevantTimes: []
  },
  {
    id: 'fruit3',
    name: 'Oranges 1kg',
    price: 120,
    image: 'https://images.pexels.com/photos/161559/background-bitter-breakfast-bright-161559.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Fruits',
    brand: 'Fresh Fruits',
    stock: 30,
    description: 'Juicy oranges packed with Vitamin C',
    dietary: ['vegan', 'organic'],
    isTimeRelevant: true,
    relevantTimes: ['morning', 'afternoon']
  },
  {
    id: 'fruit4',
    name: 'Mangoes 1kg',
    price: 250,
    image: 'https://images.pexels.com/photos/918327/pexels-photo-918327.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Fruits',
    brand: 'Fresh Fruits',
    stock: 25,
    description: 'Sweet Alphonso mangoes, king of fruits',
    dietary: ['vegan', 'organic'],
    isTimeRelevant: true,
    relevantTimes: ['afternoon', 'evening']
  },
  {
    id: 'fruit5',
    name: 'Grapes 500g',
    price: 80,
    image: 'https://images.pexels.com/photos/708777/pexels-photo-708777.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Fruits',
    brand: 'Fresh Fruits',
    stock: 20,
    description: 'Sweet green grapes, perfect for snacking',
    dietary: ['vegan', 'organic'],
    isTimeRelevant: false,
    relevantTimes: []
  },
  {
    id: 'fruit6',
    name: 'Pomegranate 500g',
    price: 150,
    image: 'https://images.pexels.com/photos/1132047/pexels-photo-1132047.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Fruits',
    brand: 'Fresh Fruits',
    stock: 15,
    description: 'Fresh pomegranate, rich in antioxidants',
    dietary: ['vegan', 'organic'],
    isTimeRelevant: false,
    relevantTimes: []
  },
  {
    id: 'fruit7',
    name: 'Papaya 1 piece',
    price: 40,
    image: 'https://images.pexels.com/photos/1132047/pexels-photo-1132047.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Fruits',
    brand: 'Fresh Fruits',
    stock: 18,
    description: 'Ripe papaya, great for digestion',
    dietary: ['vegan', 'organic'],
    isTimeRelevant: true,
    relevantTimes: ['morning']
  },
  {
    id: 'fruit8',
    name: 'Watermelon 1 piece',
    price: 80,
    image: 'https://images.pexels.com/photos/1313267/pexels-photo-1313267.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Fruits',
    brand: 'Fresh Fruits',
    stock: 12,
    description: 'Juicy watermelon, perfect for summer',
    dietary: ['vegan', 'organic'],
    isTimeRelevant: true,
    relevantTimes: ['afternoon', 'evening']
  },
  {
    id: 'fruit9',
    name: 'Pineapple 1 piece',
    price: 60,
    image: 'https://images.pexels.com/photos/947879/pexels-photo-947879.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Fruits',
    brand: 'Fresh Fruits',
    stock: 10,
    description: 'Sweet and tangy pineapple',
    dietary: ['vegan', 'organic'],
    isTimeRelevant: false,
    relevantTimes: []
  },
  {
    id: 'fruit10',
    name: 'Guava 500g',
    price: 50,
    image: 'https://images.pexels.com/photos/1132047/pexels-photo-1132047.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Fruits',
    brand: 'Fresh Fruits',
    stock: 22,
    description: 'Fresh guavas, rich in Vitamin C',
    dietary: ['vegan', 'organic'],
    isTimeRelevant: false,
    relevantTimes: []
  },

  // Snacks (10 items) - Real Indian snack images
  {
    id: 'snack1',
    name: 'Lays Classic Chips',
    price: 20,
    image: 'https://images.pexels.com/photos/4518843/pexels-photo-4518843.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Snacks',
    brand: 'Lays',
    stock: 50,
    description: 'Crispy potato chips with classic salted flavor',
    dietary: ['vegetarian'],
    isTimeRelevant: true,
    relevantTimes: ['evening', 'night']
  },
  {
    id: 'snack2',
    name: 'Kurkure Masala Munch',
    price: 15,
    image: 'https://images.pexels.com/photos/4518843/pexels-photo-4518843.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Snacks',
    brand: 'Kurkure',
    stock: 45,
    description: 'Crunchy corn snack with masala flavor',
    dietary: ['vegetarian'],
    isTimeRelevant: true,
    relevantTimes: ['evening', 'night']
  },
  {
    id: 'snack3',
    name: 'Parle-G Biscuits',
    price: 12,
    image: 'https://images.pexels.com/photos/230325/pexels-photo-230325.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Snacks',
    brand: 'Parle',
    stock: 60,
    description: 'Classic glucose biscuits, perfect with tea',
    dietary: ['vegetarian'],
    isTimeRelevant: true,
    relevantTimes: ['morning', 'evening']
  },
  {
    id: 'snack4',
    name: 'Haldiram\'s Namkeen Mix',
    price: 35,
    image: 'https://images.pexels.com/photos/4518843/pexels-photo-4518843.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Snacks',
    brand: 'Haldiram\'s',
    stock: 30,
    description: 'Traditional Indian snack mix',
    dietary: ['vegetarian'],
    isTimeRelevant: true,
    relevantTimes: ['evening', 'night']
  },
  {
    id: 'snack5',
    name: 'Bikaji Bhujia Sev',
    price: 25,
    image: 'https://images.pexels.com/photos/4518843/pexels-photo-4518843.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Snacks',
    brand: 'Bikaji',
    stock: 35,
    description: 'Crispy gram flour noodles with spices',
    dietary: ['vegetarian'],
    isTimeRelevant: true,
    relevantTimes: ['evening', 'night']
  },
  {
    id: 'snack6',
    name: 'Britannia Marie Gold',
    price: 18,
    image: 'https://images.pexels.com/photos/230325/pexels-photo-230325.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Snacks',
    brand: 'Britannia',
    stock: 40,
    description: 'Light and crispy tea-time biscuits',
    dietary: ['vegetarian'],
    isTimeRelevant: true,
    relevantTimes: ['morning', 'evening']
  },
  {
    id: 'snack7',
    name: 'Uncle Chips Spicy Treat',
    price: 22,
    image: 'https://images.pexels.com/photos/4518843/pexels-photo-4518843.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Snacks',
    brand: 'Uncle Chips',
    stock: 25,
    description: 'Spicy potato chips with Indian masala',
    dietary: ['vegetarian'],
    isTimeRelevant: true,
    relevantTimes: ['evening', 'night']
  },
  {
    id: 'snack8',
    name: 'Cadbury Dairy Milk',
    price: 45,
    image: 'https://images.pexels.com/photos/65882/chocolate-dark-coffee-confiserie-65882.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Snacks',
    brand: 'Cadbury',
    stock: 30,
    description: 'Creamy milk chocolate bar',
    dietary: ['vegetarian'],
    isTimeRelevant: true,
    relevantTimes: ['evening', 'night']
  },
  {
    id: 'snack9',
    name: 'Balaji Wafers',
    price: 20,
    image: 'https://images.pexels.com/photos/4518843/pexels-photo-4518843.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Snacks',
    brand: 'Balaji',
    stock: 35,
    description: 'Crispy potato wafers with tangy flavor',
    dietary: ['vegetarian'],
    isTimeRelevant: true,
    relevantTimes: ['evening', 'night']
  },
  {
    id: 'snack10',
    name: 'Amul Dark Chocolate',
    price: 55,
    image: 'https://images.pexels.com/photos/65882/chocolate-dark-coffee-confiserie-65882.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Snacks',
    brand: 'Amul',
    stock: 20,
    description: 'Rich dark chocolate with 55% cocoa',
    dietary: ['vegetarian'],
    isTimeRelevant: true,
    relevantTimes: ['evening', 'night']
  },

  // Indian Groceries with authentic images
  {
    id: '1',
    name: 'Tata Tea Gold 1kg',
    price: 285,
    image: 'https://images.pexels.com/photos/1638280/pexels-photo-1638280.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Groceries',
    brand: 'Tata',
    stock: 15,
    description: 'Premium blend tea leaves for the perfect cup',
    dietary: ['vegetarian'],
    isTimeRelevant: true,
    relevantTimes: ['morning', 'evening']
  },
  {
    id: '2',
    name: 'Amul Butter 500g',
    price: 58,
    image: 'https://images.pexels.com/photos/4198019/pexels-photo-4198019.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Groceries',
    brand: 'Amul',
    stock: 25,
    description: 'Fresh and creamy butter made from pure milk',
    dietary: ['vegetarian'],
    isTimeRelevant: true,
    relevantTimes: ['morning']
  },
  {
    id: '3',
    name: 'Maggi 2-Minute Noodles',
    price: 14,
    image: 'https://images.pexels.com/photos/4518843/pexels-photo-4518843.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Groceries',
    brand: 'Maggi',
    stock: 50,
    description: 'Quick and tasty instant noodles',
    dietary: ['vegetarian'],
    isTimeRelevant: true,
    relevantTimes: ['evening', 'night']
  },
  {
    id: '4',
    name: 'Basmati Rice 1kg',
    price: 180,
    image: 'https://images.pexels.com/photos/723198/pexels-photo-723198.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Groceries',
    brand: 'India Gate',
    stock: 20,
    description: 'Premium long grain basmati rice',
    dietary: ['vegan', 'gluten-free'],
    isTimeRelevant: false,
    relevantTimes: []
  },
  {
    id: '5',
    name: 'Britannia Good Day Cookies',
    price: 25,
    image: 'https://images.pexels.com/photos/230325/pexels-photo-230325.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Groceries',
    brand: 'Britannia',
    stock: 30,
    description: 'Delicious butter cookies for tea time',
    dietary: ['vegetarian'],
    isTimeRelevant: true,
    relevantTimes: ['evening']
  },

  // Household Items
  {
    id: '7',
    name: 'Surf Excel Detergent 1kg',
    price: 165,
    image: 'https://images.pexels.com/photos/4239091/pexels-photo-4239091.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Household',
    brand: 'Surf Excel',
    stock: 12,
    description: 'Powerful stain removal detergent powder',
    dietary: [],
    isTimeRelevant: false,
    relevantTimes: []
  },
  {
    id: 'house1',
    name: 'Vim Dishwash Gel 500ml',
    price: 85,
    image: 'https://images.pexels.com/photos/4239091/pexels-photo-4239091.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Household',
    brand: 'Vim',
    stock: 20,
    description: 'Effective dishwashing gel for sparkling clean dishes',
    dietary: [],
    isTimeRelevant: false,
    relevantTimes: []
  },
  {
    id: 'house2',
    name: 'Lizol Floor Cleaner 500ml',
    price: 95,
    image: 'https://images.pexels.com/photos/4239091/pexels-photo-4239091.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Household',
    brand: 'Lizol',
    stock: 15,
    description: 'Disinfectant floor cleaner with fresh fragrance',
    dietary: [],
    isTimeRelevant: false,
    relevantTimes: []
  },

  // Electronics
  {
    id: '11',
    name: 'boAt Earphones',
    price: 1299,
    image: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Electronics',
    brand: 'boAt',
    stock: 8,
    description: 'Wireless Bluetooth earphones with deep bass',
    dietary: [],
    isTimeRelevant: false,
    relevantTimes: []
  },
  {
    id: 'elec1',
    name: 'Mi Power Bank 10000mAh',
    price: 1499,
    image: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Electronics',
    brand: 'Mi',
    stock: 12,
    description: 'Fast charging power bank with dual USB ports',
    dietary: [],
    isTimeRelevant: false,
    relevantTimes: []
  },

  // Personal Care
  {
    id: '16',
    name: 'Dove Soap 100g',
    price: 45,
    image: 'https://images.pexels.com/photos/298663/pexels-photo-298663.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Personal Care',
    brand: 'Dove',
    stock: 40,
    description: 'Moisturizing beauty bar soap',
    dietary: [],
    isTimeRelevant: false,
    relevantTimes: []
  },
  {
    id: 'care1',
    name: 'Colgate Toothpaste 200g',
    price: 65,
    image: 'https://images.pexels.com/photos/298663/pexels-photo-298663.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Personal Care',
    brand: 'Colgate',
    stock: 35,
    description: 'Advanced whitening toothpaste for healthy teeth',
    dietary: [],
    isTimeRelevant: false,
    relevantTimes: []
  },

  // Beverages
  {
    id: '19',
    name: 'Coca Cola 600ml',
    price: 40,
    image: 'https://images.pexels.com/photos/50593/coca-cola-cold-drink-soft-drink-coke-50593.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Beverages',
    brand: 'Coca Cola',
    stock: 45,
    description: 'Refreshing cola drink',
    dietary: ['vegetarian'],
    isTimeRelevant: true,
    relevantTimes: ['afternoon', 'evening']
  },
  {
    id: 'bev1',
    name: 'Frooti Mango Drink 200ml',
    price: 20,
    image: 'https://images.pexels.com/photos/50593/coca-cola-cold-drink-soft-drink-coke-50593.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Beverages',
    brand: 'Frooti',
    stock: 50,
    description: 'Fresh mango flavored drink',
    dietary: ['vegetarian'],
    isTimeRelevant: true,
    relevantTimes: ['afternoon', 'evening']
  },
  {
    id: 'bev2',
    name: 'Bisleri Water 1L',
    price: 20,
    image: 'https://images.pexels.com/photos/50593/coca-cola-cold-drink-soft-drink-coke-50593.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Beverages',
    brand: 'Bisleri',
    stock: 100,
    description: 'Pure drinking water',
    dietary: ['vegan'],
    isTimeRelevant: false,
    relevantTimes: []
  }
];

export const categories = ['All', 'Vegetables', 'Fruits', 'Snacks', 'Groceries', 'Household', 'Electronics', 'Personal Care', 'Beverages'];
export const brands = ['All', 'Fresh Farm', 'Fresh Fruits', 'Lays', 'Kurkure', 'Parle', 'Haldiram\'s', 'Bikaji', 'Britannia', 'Uncle Chips', 'Cadbury', 'Balaji', 'Amul', 'Tata', 'Maggi', 'India Gate', 'Surf Excel', 'Vim', 'Lizol', 'boAt', 'Mi', 'Dove', 'Colgate', 'Coca Cola', 'Frooti', 'Bisleri'];
export const dietaryOptions = ['vegetarian', 'vegan', 'organic', 'gluten-free'];